version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - dev-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - dev-network

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - dev-network

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    volumes:
      - ./terraform:/workspace
    working_dir: /workspace
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - dev-network

volumes:
  jenkins_home:
  db_data:
  nexus-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  

networks:
  dev-network:






